spring:
  application:
    name: Online Goods Store
    group: ru.anokhin.dev
    version: 0.0.1
  security:
    user:
      name: user
      password: user


  liquibase:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/STORE
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000

  jpa:
    database: PostgreSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true


server:
  address: localhost
  servlet:
#    context-path: /online-goods-store
    encoding:
      charset: UTF-8
      enabled: true


